; HEADER_BLOCK_START
; generated by OrcaSlicer 2.2.0 on 2025-11-02 at 11:05:52
; total layer number: 1
; filament_density: 1.24
; filament_diameter: 1.75
; max_z_height: 0.20
; HEADER_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 48x48 740
; iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAB8ElEQVR4Ae2Z20oCURSGN1aWWh7zkF
; ZODnQRBRIUVFCGUBISQxdCQWR10QlCEIJAEooKKpyrAq98BB9hHsFH8BF8hIl1IUyT2pz2zB7aH6wb
; HeRn1v6We88gRKFQKBSScbhdfmRHRmcS6eRLpT3HP3c86UUO2YnJAsez9ZooLfiM+G7AXZ+ulFvy8N
; 2C7+AaRCK+7GapX3BpwZKCa4npBgSJXZ01lYSXVrx8LQyHggyyEtc8m4E7qja8tBsTaytFZAW9RNVa
; keJhw7Ql1R2PRoWXCo593CoVVc+SwiI4/CBIhzM8NsFBMrOC9+oG0gPIZUV4eTdULylcourphmLBA/
; ndKinB5TVwP/XXPoaU6rmf8mU2Smy9JtqlfgkOWwLm47HD1muiHSr1+SZC5h9dgLUVPi40SA8fuzkX
; HB4301fi8dXlop4NGs7ybq0r+19wxmPpeOlSICU4iOuciqo7CMGSCnJ7fOrr3dLwoYM8j/QAssw+3b
; fNDp58feiMpZgMMgKzBY9enAgIB+6lBQ7nuIXxiP2ENhINYxFck6h6AMGNGrfB/Zw+UbUCexI9ghsq
; qla6gqsdt5HToyYiCaWCg6jEPisFwQed4uB0NeTzMoh0/DvbVbnggVy2iuwECJ64u22ZPh6NxLYvNy
; gUCuX/8A1H1q6IyOHingAAAABJRU5ErkJggg==
; thumbnail end
; THUMBNAIL_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 300x300 3308
; iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAYAAAB5fY51AAAJdklEQVR4Ae3d7Y5VVxnA8U1TDwJaZ0
; odxxlgZoC0aYIRjSbywTpRsZEaxaTRYIJMhNggVSHFqA1kNEpraxSN0cRPXAKXwCVwCVzCXMLYNfbA
; dHqGOWef/bJefr/kn/RTA0O7s/fT9axWFQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAyfvMt165Hnrm4IGZCiBG4QG18NYvHpz47983Q+Gvnz38/HIF
; EJNPn/nq2vBBtb2Vu3c2wttWBRCDubUL90Y9rLYX3rZ8IgK92X908fTSO7ce7fWw2v62dej0qfMVQJ
; dmv/fq+rgPqp298KPzd71tAa0Lb1VHbr31sO7Dalj4e4S/VwXQhjA8n/ZBZSAPtCp8vs1f/dn9Jh9W
; Owfyjj8AUzvw4onV8CbU1sPKQB5oRBiOt/2gMpAHptLUYN1AHmhV04P1aT4R7SMCI+3cA4wlA3ngI3
; bbA4yl8LYVfo0VULZx9gBjKfxafSJCgSbdA4ylMJB3/AEKMs0eYAwZyEMB+j6u0HRhIO/4A2QoluMK
; bb1tVUD6wmdTSoP1ad62HH+AhKU6WJ/mbctAHhLUxx5gLNlHhETkNlivm31EiFyug/W6Of4AEWr7gr
; 3UM5CHSHR1wV7q2UeEnpU8WK+bfUToWGnHFZrOPiJ0xGC9mQzkoUWxXrCXegby0LDYL9hLPfuI0JAS
; 9gBjKbxt+USEGgzW+8k+Ikwo9Qv2csg+IuzBHmBc2UeEXTiuEGcG8rCNPcA0cvyB4tkDTCv7iBTLHm
; C62UekGI4r5FEYyIc35ApyZbCeV/YRyZI9wLwzkCcb9gDLyPEHkmcPsLzsI5Icg/WyC3/29hFJgj1A
; hcInon1EomUPUKMKn4j2EYmK4wp6WgbyRCG87husa9wcf6A3BuuqkwsC6Zw9QE2bgTytM1hXk7kgkN
; YYrKuN7CPSKBfsqYsM5JmaC/bUZS4IpDaDdfWVCwIZm+MKiqEwkHf8gaeyB6iYMpBnpDDsdFxBsWYg
; z2Mu2FMK2UfEBXtKLhcEFshgXSlnH7Egjisol+wjZsweoHLMPmKG7AEq5xx/yIQ9QJWU4w8JsweoEr
; OPmCCDdZWefcQEOK4gPck+YsQM1qWPZyAfmfAHEYaNKf1DJHWdgXwE7AFK42cfsUf2AKV62UfskMG6
; NH32ETvggj2p2ewjtsAeoNRe9hEb5LiC1H4G8lOyByh1n+MPNYTXU3uAUj8ZyE/AHqAURwbyT2GwLs
; WXgfwIButSvNlH/JA9QCmdih7I2wOU0qvICwLtAUppV8QFgfYApXzK+oJAe4BSfmU3kHdcQcq/MJBP
; /viD4wpSOSW7jxheDw3WpTJL6oJAg3VJSewj2gOUtL0o9xEN1iXtVlT7iAbrkvaq9+MPLtiTNGm97C
; MeePHEqgv2JNWp031Eg3VJTdTqPqLjCpKarpV9RIN1SW3V2EDeBXuSumqqgfxgYf50Sr9ZSekX3rY+
; eXJl8k/ED550p+ffWHt0/F9/Seo3LCnNjv/7/c35a1c2PjH32dWqrplvf+Pe8vt/SOo3Limtlv/2p8
; 2ZV7/5oGrC/uVj5xd/++uN4//5a1I/BEnxt/ibX27uX1laq5oUPhEP//C1+yv/eCepH4akOAtvVc//
; 4LsPnp2daW/P8LlXztw9evumty1JtTty++bmoS9/8W7VBQN5SXUKg/XPvbE23WC9rjCQX3r3dlI/ME
; n9dOzOreYG63UNFuZXF2++6RNR0q4t3Li62ctb1SjhE3H23FnHHyR9pDBYn33tOw+eOXRwuYrNoS99
; 4bqBvKTQ4u+vbx546WTc/xed4UDe8QepzMJb1dylCxutHldoWjj+cOzPbyf1g5Y0XeG4wqe+9pV7VY
; rC29bnf/Vzn4hS5oXjClEN1qdhH1HKt+FgvcqJfUQpv8IeYPSD9brsI0p51MkeYCyGA3lvW1J6dboH
; GAv7iFJa9boHGAv7iFL8Lb233v8eYCy2BvL2EaUoa+WCvdTZR5TiKuo9wFjYR5T6LwzWD556eb1ibw
; byUj+Fwfrc5YtlD9brso8oddfRP/4u3T3AWNhHlNovmz3AGOwbDGbsI0rNZ7DeIvuIUnMlccFe6uwj
; StNV1B5gLAzkpckrcg8wFo4/SONlDzAiBvLS7tkDjJCBvPTx7AFGzEBe+n8G6wkJA3n7iCo1g/UEGc
; irtOwBZsAFgSqhsAf43NfP3K9I32BhfnXhxlWfiMoye4AZCp+IH/ynXccflE32AAsQLgg88vYNb1tK
; OnuABRkO5B1/UGqFt6oXfvL6I8cVCmQfUSkVjiu4YK9wjy8IdPxBkRaOK8xfu+K4Ak/YR1SMDQfrFe
; xkH1ExZQ+QPdlHVN/ZA2Ri9hHVR/YAqc0+orrKBXs0xj6i2swFezQu7CMu3nzTJ6IaLQzWvVXRivCJ
; OHvurOMPmjp7gHQm7CMayKtuYQ/w4KmX1yvoioG8Jm3rgr1LFwzW6Y99RI1TuGDPHiBReLyP6BNRI3
; LBHtHZNxjM2EfU9gzWiZ59RIVcsEcy7COWmz1AkmUgX1b2AEme4w/5Zw+Q7NhHzDN7gGRrayBvHzGb
; XLBH9oYD+TCcTelfTj1peFzBYJ1i2EdMszBYtwdIkQzk02lrD/DyRYN1CAN5xx/izR4g7GAfMc7sAc
; IuwkPLPmIc2QOEMR146eSafcT+sgcIEwpvW3M//fFD+4jdFd6qDr/+/YeOK0BN9hG7yR4gNMTxh/YK
; xxXmr11xXAGaZiDfbMPBegW0wwWBzWQPEDrigsD6uWAPehIG8vYRx89gHXpmIL93LtiDyLggcHTH7t
; xywR7EaLAwv+qCwCfZA4TIhU/E2XNniz7+YA8QElPqBYFhD9AFe5CgkgbyK/98d3Pu0oUNxxUgcbnv
; I7pgDzKT6wWBBuuQsVz2Ee0BQiFS30cMe4Au2IOCpLiPaA8QCjccyMf+tmUPENgS8/EHe4DASLHtIy
; 69t24PENjd1kA+gn1EF+wBY+lzH9EeIFBL1/uIYbBuDxCorYuBfBisz12+aLAONKOtfUR7gEArmt5H
; tAcItGrfYDAz7T6iwTrQqbr7iOGCPXuAQOcm2Ue0BwhEYa+BvD1AICqjjj/YAwSiNhzI2wMEkhAG8v
; YAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADy
; 8D/ctT+06sVWQQAAAABJRU5ErkJggg==
; thumbnail end
; THUMBNAIL_BLOCK_END

; external perimeters extrusion width = 0.40mm
; perimeters extrusion width = 0.40mm
; infill extrusion width = 0.40mm
; solid infill extrusion width = 0.40mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.40mm

; EXECUTABLE_BLOCK_START
EXCLUDE_OBJECT_DEFINE NAME=Cube_id_0_copy_0 CENTER=125,122.5 POLYGON=[[105,102.5],[145,102.5],[145,142.5],[105,142.5],[105,102.5]]
M73 P0 R0
;TYPE:Custom
PRINT_START EXTRUDER_TEMP=245 BED_TEMP=65
G90
G21
M83 ; use relative distances for extrusion
; filament start gcode
M106 P3 S255


SET_PRESSURE_ADVANCE ADVANCE=0.02; Override pressure advance value
M106 S0
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.2
G92 E0

G1 E-.5 F2100
;AFTER_LAYER_CHANGE
;0.2
;_SET_FAN_SPEED_CHANGING_LAYER
SET_VELOCITY_LIMIT ACCEL=5000
SET_VELOCITY_LIMIT SQUARE_CORNER_VELOCITY=12
; printing object Cube id:0 copy 0
EXCLUDE_OBJECT_START NAME=Cube_id_0_copy_0
G1 X144.65 Y142.15 F36000
M73 P1 R0
G1 Z.2
M73 P1 R0
G1 E.5 F2100
;TYPE:Outer wall
;WIDTH:0.4
G1 F15000
G1 X105.35 Y142.15 E1.08052
M73 P2 R0
G1 X105.35 Y102.85 E1.08052
M73 P2 R0
M73 P3 R0
G1 X144.65 Y102.85 E1.08052
M73 P3 R0
M73 P4 R0
G1 X144.65 Y142.11 E1.07942
M73 P4 R0
G1 E-.36 F2100
;WIPE_START
G1 F15000
G1 X143.65 Y142.111 E-.14
;WIPE_END
M73 P5 R0
G1 X144.543 Y103.684 F36000
M73 P5 R0
G1 E.5 F2100
;TYPE:Bottom surface
;WIDTH:0.40218
G1 F15000
G1 X143.977 Y103.118 E.02213
G1 X143.469 Y103.118 E.01405
G1 X144.382 Y104.031 E.03572
M73 P6 R0
G1 X144.382 Y104.539 E.01405
M73 P6 R0
G1 X142.961 Y103.118 E.0556
G1 X142.453 Y103.118 E.01405
G1 X144.382 Y105.047 E.07547
G1 X144.382 Y105.555 E.01405
G1 X141.945 Y103.118 E.09535
G1 X141.437 Y103.118 E.01405
G1 X144.382 Y106.063 E.11523
G1 X144.382 Y106.571 E.01405
G1 X140.929 Y103.118 E.1351
M73 P7 R0
G1 X140.421 Y103.118 E.01405
M73 P7 R0
G1 X144.382 Y107.079 E.15498
G1 X144.382 Y107.587 E.01405
G1 X139.913 Y103.118 E.17485
G1 X139.404 Y103.118 E.01405
G1 X144.382 Y108.096 E.19473
M73 P8 R0
G1 X144.382 Y108.604 E.01405
M73 P8 R0
G1 X138.896 Y103.118 E.2146
G1 X138.388 Y103.118 E.01405
G1 X144.382 Y109.112 E.23448
G1 X144.382 Y109.62 E.01405
G1 X137.88 Y103.118 E.25436
M73 P9 R0
G1 X137.372 Y103.118 E.01405
M73 P9 R0
G1 X144.382 Y110.128 E.27423
G1 X144.382 Y110.636 E.01405
G1 X136.864 Y103.118 E.29411
G1 X136.356 Y103.118 E.01405
G1 X144.382 Y111.144 E.31398
M73 P10 R0
G1 X144.382 Y111.652 E.01405
M73 P10 R0
G1 X135.848 Y103.118 E.33386
G1 X135.34 Y103.118 E.01405
G1 X144.382 Y112.16 E.35373
M73 P11 R0
G1 X144.382 Y112.668 E.01405
M73 P11 R0
G1 X134.832 Y103.118 E.37361
G1 X134.324 Y103.118 E.01405
G1 X144.382 Y113.176 E.39349
G1 X144.382 Y113.684 E.01405
G1 X133.816 Y103.118 E.41336
M73 P12 R0
G1 X133.308 Y103.118 E.01405
M73 P12 R0
G1 X144.382 Y114.192 E.43324
G1 X144.382 Y114.7 E.01405
G1 X132.8 Y103.118 E.45311
M73 P13 R0
G1 X132.291 Y103.118 E.01405
M73 P13 R0
G1 X144.382 Y115.209 E.47299
G1 X144.382 Y115.717 E.01405
G1 X131.783 Y103.118 E.49286
M73 P14 R0
G1 X131.275 Y103.118 E.01405
M73 P14 R0
G1 X144.382 Y116.225 E.51274
G1 X144.382 Y116.733 E.01405
G1 X130.767 Y103.118 E.53262
M73 P15 R0
G1 X130.259 Y103.118 E.01405
M73 P15 R0
G1 X144.382 Y117.241 E.55249
G1 X144.382 Y117.749 E.01405
G1 X129.751 Y103.118 E.57237
M73 P16 R0
G1 X129.243 Y103.118 E.01405
M73 P16 R0
G1 X144.382 Y118.257 E.59224
G1 X144.382 Y118.765 E.01405
G1 X128.735 Y103.118 E.61212
M73 P17 R0
G1 X128.227 Y103.118 E.01405
M73 P17 R0
G1 X144.382 Y119.273 E.63199
G1 X144.382 Y119.781 E.01405
G1 X127.719 Y103.118 E.65187
M73 P18 R0
G1 X127.211 Y103.118 E.01405
M73 P18 R0
G1 X144.382 Y120.289 E.67175
M73 P19 R0
G1 X144.382 Y120.797 E.01405
M73 P19 R0
G1 X126.703 Y103.118 E.69162
G1 X126.195 Y103.118 E.01405
G1 X144.382 Y121.305 E.7115
M73 P20 R0
G1 X144.382 Y121.813 E.01405
M73 P20 R0
G1 X125.687 Y103.118 E.73137
G1 X125.178 Y103.118 E.01405
G1 X144.382 Y122.322 E.75125
M73 P21 R0
G1 X144.382 Y122.83 E.01405
M73 P21 R0
G1 X124.67 Y103.118 E.77112
M73 P22 R0
G1 X124.162 Y103.118 E.01405
M73 P22 R0
G1 X144.382 Y123.338 E.791
G1 X144.382 Y123.846 E.01405
G1 X123.654 Y103.118 E.81088
M73 P23 R0
G1 X123.146 Y103.118 E.01405
M73 P23 R0
G1 X144.382 Y124.354 E.83075
M73 P24 R0
G1 X144.382 Y124.862 E.01405
M73 P24 R0
G1 X122.638 Y103.118 E.85063
G1 X122.13 Y103.118 E.01405
G1 X144.382 Y125.37 E.8705
M73 P25 R0
G1 X144.382 Y125.878 E.01405
M73 P25 R0
G1 X121.622 Y103.118 E.89038
M73 P26 R0
G1 X121.114 Y103.118 E.01405
M73 P26 R0
G1 X144.382 Y126.386 E.91025
G1 X144.382 Y126.894 E.01405
G1 X120.606 Y103.118 E.93013
M73 P27 R0
G1 X120.098 Y103.118 E.01405
M73 P27 R0
G1 X144.382 Y127.402 E.95001
M73 P28 R0
G1 X144.382 Y127.91 E.01405
M73 P28 R0
G1 X119.59 Y103.118 E.96988
G1 X119.082 Y103.118 E.01405
M73 P29 R0
G1 X144.382 Y128.418 E.98976
M73 P29 R0
G1 X144.382 Y128.926 E.01405
G1 X118.574 Y103.118 E1.00963
M73 P30 R0
G1 X118.066 Y103.118 E.01405
M73 P30 R0
G1 X144.382 Y129.434 E1.02951
M73 P31 R0
G1 X144.382 Y129.943 E.01405
M73 P31 R0
G1 X117.557 Y103.118 E1.04938
M73 P32 R0
G1 X117.049 Y103.118 E.01405
M73 P32 R0
G1 X144.382 Y130.451 E1.06926
G1 X144.382 Y130.959 E.01405
G1 X116.541 Y103.118 E1.08914
M73 P33 R0
G1 X116.033 Y103.118 E.01405
M73 P33 R0
G1 X144.382 Y131.467 E1.10901
M73 P34 R0
G1 X144.382 Y131.975 E.01405
M73 P34 R0
G1 X115.525 Y103.118 E1.12889
M73 P35 R0
G1 X115.017 Y103.118 E.01405
M73 P35 R0
G1 X144.382 Y132.483 E1.14876
M73 P36 R0
G1 X144.382 Y132.991 E.01405
M73 P36 R0
G1 X114.509 Y103.118 E1.16864
G1 X114.001 Y103.118 E.01405
G1 X144.382 Y133.499 E1.18851
M73 P37 R0
G1 X144.382 Y134.007 E.01405
M73 P37 R0
G1 X113.493 Y103.118 E1.20839
M73 P38 R0
G1 X112.985 Y103.118 E.01405
M73 P38 R0
G1 X144.382 Y134.515 E1.22827
M73 P39 R0
G1 X144.382 Y135.023 E.01405
M73 P39 R0
G1 X112.477 Y103.118 E1.24814
M73 P40 R0
G1 X111.969 Y103.118 E.01405
M73 P40 R0
G1 X144.382 Y135.531 E1.26802
M73 P41 R0
G1 X144.382 Y136.039 E.01405
M73 P41 R0
G1 X111.461 Y103.118 E1.28789
M73 P42 R0
G1 X110.953 Y103.118 E.01405
M73 P42 R0
G1 X144.382 Y136.547 E1.30777
M73 P43 R0
G1 X144.382 Y137.056 E.01405
M73 P43 R0
G1 X110.444 Y103.118 E1.32764
G1 X109.936 Y103.118 E.01405
M73 P44 R0
G1 X144.382 Y137.564 E1.34752
M73 P44 R0
G1 X144.382 Y138.072 E.01405
G1 X109.428 Y103.118 E1.3674
M73 P45 R0
G1 X108.92 Y103.118 E.01405
M73 P45 R0
G1 X144.382 Y138.58 E1.38727
M73 P46 R0
G1 X144.382 Y139.088 E.01405
M73 P46 R0
G1 X108.412 Y103.118 E1.40715
M73 P47 R0
G1 X107.904 Y103.118 E.01405
M73 P47 R0
G1 X144.382 Y139.596 E1.42702
M73 P48 R0
G1 X144.382 Y140.104 E.01405
M73 P48 R0
G1 X107.396 Y103.118 E1.4469
M73 P49 R0
G1 X106.888 Y103.118 E.01405
M73 P49 R0
G1 X144.382 Y140.612 E1.46677
M73 P50 R0
G1 X144.382 Y141.12 E.01405
M73 P50 R0
G1 X106.38 Y103.118 E1.48665
M73 P51 R0
G1 X105.872 Y103.118 E.01405
M73 P51 R0
G1 X144.382 Y141.628 E1.50653
M73 P52 R0
G1 X144.382 Y141.882 E.00703
M73 P52 R0
G1 X144.128 Y141.882 E.00703
G1 X105.618 Y103.372 E1.50652
M73 P53 R0
G1 X105.618 Y103.88 E.01405
M73 P53 R0
G1 X143.62 Y141.882 E1.48665
M73 P54 R0
G1 X143.112 Y141.882 E.01405
M73 P54 R0
G1 X105.618 Y104.388 E1.46677
M73 P55 R0
G1 X105.618 Y104.896 E.01405
M73 P55 R0
G1 X142.604 Y141.882 E1.4469
M73 P56 R0
G1 X142.096 Y141.882 E.01405
M73 P56 R0
G1 X105.618 Y105.404 E1.42702
M73 P57 R0
G1 X105.618 Y105.912 E.01405
M73 P57 R0
G1 X141.588 Y141.882 E1.40715
M73 P58 R0
G1 X141.08 Y141.882 E.01405
M73 P58 R0
G1 X105.618 Y106.42 E1.38727
M73 P59 R0
G1 X105.618 Y106.928 E.01405
M73 P59 R0
G1 X140.572 Y141.882 E1.36739
M73 P60 R0
G1 X140.064 Y141.882 E.01405
M73 P60 R0
G1 X105.618 Y107.436 E1.34752
M73 P61 R0
G1 X105.618 Y107.945 E.01405
M73 P61 R0
G1 X139.555 Y141.882 E1.32764
M73 P62 R0
G1 X139.047 Y141.882 E.01405
M73 P62 R0
G1 X105.618 Y108.453 E1.30777
M73 P63 R0
G1 X105.618 Y108.961 E.01405
M73 P63 R0
G1 X138.539 Y141.882 E1.28789
M73 P64 R0
G1 X138.031 Y141.882 E.01405
M73 P64 R0
G1 X105.618 Y109.469 E1.26802
M73 P65 R0
G1 X105.618 Y109.977 E.01405
M73 P65 R0
G1 X137.523 Y141.882 E1.24814
M73 P66 R0
G1 X137.015 Y141.882 E.01405
M73 P66 R0
G1 X105.618 Y110.485 E1.22826
G1 X105.618 Y110.993 E.01405
M73 P67 R0
G1 X136.507 Y141.882 E1.20839
M73 P67 R0
G1 X135.999 Y141.882 E.01405
G1 X105.618 Y111.501 E1.18851
M73 P68 R0
G1 X105.618 Y112.009 E.01405
M73 P68 R0
G1 X135.491 Y141.882 E1.16864
M73 P69 R0
G1 X134.983 Y141.882 E.01405
M73 P69 R0
G1 X105.618 Y112.517 E1.14876
M73 P70 R0
G1 X105.618 Y113.025 E.01405
M73 P70 R0
G1 X134.475 Y141.882 E1.12889
M73 P71 R0
G1 X133.967 Y141.882 E.01405
M73 P71 R0
G1 X105.618 Y113.533 E1.10901
G1 X105.618 Y114.041 E.01405
M73 P72 R0
G1 X133.459 Y141.882 E1.08913
M73 P72 R0
G1 X132.951 Y141.882 E.01405
G1 X105.618 Y114.549 E1.06926
M73 P73 R0
G1 X105.618 Y115.057 E.01405
M73 P73 R0
G1 X132.443 Y141.882 E1.04938
M73 P74 R0
G1 X131.934 Y141.882 E.01405
M73 P74 R0
G1 X105.618 Y115.566 E1.02951
M73 P75 R0
G1 X105.618 Y116.074 E.01405
M73 P75 R0
G1 X131.426 Y141.882 E1.00963
G1 X130.918 Y141.882 E.01405
G1 X105.618 Y116.582 E.98976
M73 P76 R0
G1 X105.618 Y117.09 E.01405
M73 P76 R0
G1 X130.41 Y141.882 E.96988
M73 P77 R0
G1 X129.902 Y141.882 E.01405
M73 P77 R0
G1 X105.618 Y117.598 E.95
M73 P78 R0
G1 X105.618 Y118.106 E.01405
M73 P78 R0
G1 X129.394 Y141.882 E.93013
G1 X128.886 Y141.882 E.01405
G1 X105.618 Y118.614 E.91025
M73 P79 R0
G1 X105.618 Y119.122 E.01405
M73 P79 R0
G1 X128.378 Y141.882 E.89038
M73 P80 R0
G1 X127.87 Y141.882 E.01405
M73 P80 R0
G1 X105.618 Y119.63 E.8705
G1 X105.618 Y120.138 E.01405
G1 X127.362 Y141.882 E.85063
M73 P81 R0
G1 X126.854 Y141.882 E.01405
M73 P81 R0
G1 X105.618 Y120.646 E.83075
M73 P82 R0
G1 X105.618 Y121.154 E.01405
M73 P82 R0
G1 X126.346 Y141.882 E.81087
G1 X125.838 Y141.882 E.01405
G1 X105.618 Y121.662 E.791
M73 P83 R0
G1 X105.618 Y122.17 E.01405
M73 P83 R0
G1 X125.33 Y141.882 E.77112
M73 P84 R0
G1 X124.821 Y141.882 E.01405
M73 P84 R0
G1 X105.618 Y122.679 E.75125
G1 X105.618 Y123.187 E.01405
G1 X124.313 Y141.882 E.73137
M73 P85 R0
G1 X123.805 Y141.882 E.01405
M73 P85 R0
G1 X105.618 Y123.695 E.7115
G1 X105.618 Y124.203 E.01405
G1 X123.297 Y141.882 E.69162
M73 P86 R0
G1 X122.789 Y141.882 E.01405
M73 P86 R0
G1 X105.618 Y124.711 E.67174
M73 P87 R0
G1 X105.618 Y125.219 E.01405
M73 P87 R0
G1 X122.281 Y141.882 E.65187
G1 X121.773 Y141.882 E.01405
G1 X105.618 Y125.727 E.63199
M73 P88 R0
G1 X105.618 Y126.235 E.01405
M73 P88 R0
G1 X121.265 Y141.882 E.61212
G1 X120.757 Y141.882 E.01405
G1 X105.618 Y126.743 E.59224
M73 P89 R0
G1 X105.618 Y127.251 E.01405
M73 P89 R0
G1 X120.249 Y141.882 E.57237
G1 X119.741 Y141.882 E.01405
G1 X105.618 Y127.759 E.55249
M73 P90 R0
G1 X105.618 Y128.267 E.01405
M73 P90 R0
G1 X119.233 Y141.882 E.53261
G1 X118.725 Y141.882 E.01405
G1 X105.618 Y128.775 E.51274
M73 P91 R0
G1 X105.618 Y129.283 E.01405
M73 P91 R0
G1 X118.217 Y141.882 E.49286
G1 X117.708 Y141.882 E.01405
G1 X105.618 Y129.792 E.47299
M73 P92 R0
G1 X105.618 Y130.3 E.01405
M73 P92 R0
G1 X117.2 Y141.882 E.45311
G1 X116.692 Y141.882 E.01405
G1 X105.618 Y130.808 E.43324
M73 P93 R0
G1 X105.618 Y131.316 E.01405
M73 P93 R0
G1 X116.184 Y141.882 E.41336
G1 X115.676 Y141.882 E.01405
G1 X105.618 Y131.824 E.39348
M73 P94 R0
G1 X105.618 Y132.332 E.01405
M73 P94 R0
G1 X115.168 Y141.882 E.37361
G1 X114.66 Y141.882 E.01405
G1 X105.618 Y132.84 E.35373
G1 X105.618 Y133.348 E.01405
G1 X114.152 Y141.882 E.33386
M73 P95 R0
G1 X113.644 Y141.882 E.01405
M73 P95 R0
G1 X105.618 Y133.856 E.31398
G1 X105.618 Y134.364 E.01405
G1 X113.136 Y141.882 E.29411
M73 P96 R0
G1 X112.628 Y141.882 E.01405
M73 P96 R0
G1 X105.618 Y134.872 E.27423
G1 X105.618 Y135.38 E.01405
G1 X112.12 Y141.882 E.25435
G1 X111.612 Y141.882 E.01405
G1 X105.618 Y135.888 E.23448
M73 P97 R0
G1 X105.618 Y136.396 E.01405
M73 P97 R0
G1 X111.104 Y141.882 E.2146
G1 X110.595 Y141.882 E.01405
G1 X105.618 Y136.905 E.19473
G1 X105.618 Y137.413 E.01405
G1 X110.087 Y141.882 E.17485
M73 P98 R0
G1 X109.579 Y141.882 E.01405
M73 P98 R0
G1 X105.618 Y137.921 E.15498
G1 X105.618 Y138.429 E.01405
G1 X109.071 Y141.882 E.1351
G1 X108.563 Y141.882 E.01405
G1 X105.618 Y138.937 E.11522
G1 X105.618 Y139.445 E.01405
G1 X108.055 Y141.882 E.09535
M73 P99 R0
G1 X107.547 Y141.882 E.01405
M73 P99 R0
G1 X105.618 Y139.953 E.07547
G1 X105.618 Y140.461 E.01405
G1 X107.039 Y141.882 E.0556
G1 X106.531 Y141.882 E.01405
G1 X105.618 Y140.969 E.03572
G1 X105.618 Y141.477 E.01405
G1 X106.184 Y142.043 E.02213
; stop printing object Cube id:0 copy 0
G1 E-.36 F2100
;WIPE_START
G1 F15000
G1 X105.618 Y141.477 E-.11201
G1 X105.618 Y141.277 E-.02799
;WIPE_END
EXCLUDE_OBJECT_END NAME=Cube_id_0_copy_0
M106 S0
;TYPE:Custom
; filament end gcode 
M106 P3 S0
PRINT_END
M73 P100 R0
; EXECUTABLE_BLOCK_END

; filament used [mm] = 122.16
; filament used [cm3] = 0.29
; filament used [g] = 0.36
; filament cost = 0.01
; total filament used [g] = 0.36
; total filament cost = 0.01
; total layers count = 1
; estimated printing time (normal mode) = 27s

; CONFIG_BLOCK_START
; accel_to_decel_enable = 0
; accel_to_decel_factor = 50%
; activate_air_filtration = 0
; activate_chamber_temp_control = 0
; adaptive_bed_mesh_margin = 0
; adaptive_pressure_advance = 0
; adaptive_pressure_advance_bridges = 0
; adaptive_pressure_advance_model = "0,0,0\n0,0,0"
; adaptive_pressure_advance_overhangs = 0
; additional_cooling_fan_speed = 70
; alternate_extra_wall = 0
; auxiliary_fan = 0
; bbl_calib_mark_logo = 1
; bbl_use_printhost = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_exclude_area = 0x0
; bed_mesh_max = 99999,99999
; bed_mesh_min = -99999,-99999
; bed_mesh_probe_distance = 50,50
; before_layer_change_gcode = ;BEFORE_LAYER_CHANGE\n;[layer_z]\nG92 E0\n
; best_object_pos = 0.5,0.5
; bottom_shell_layers = 5
; bottom_shell_thickness = 0
; bottom_solid_infill_flow_ratio = 1
; bottom_surface_pattern = monotonic
; bridge_acceleration = 50%
; bridge_angle = 0
; bridge_density = 100%
; bridge_flow = 1
; bridge_no_support = 0
; bridge_speed = 100
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_object_gap = 0.1
; brim_type = auto_brim
; brim_width = 5
; chamber_temperature = 0
; change_extrusion_role_gcode = 
; change_filament_gcode = 
; close_fan_the_first_x_layers = 2
; complete_print_exhaust_fan_speed = 70
; cool_plate_temp = 35
; cool_plate_temp_initial_layer = 35
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; counterbore_hole_bridging = none
; curr_bed_type = High Temp Plate
; default_acceleration = 30000
; default_filament_colour = ""
; default_filament_profile = "Voron Generic ABS"
; default_jerk = 12
; default_print_profile = 0.20mm Standard @Voron
; deretraction_speed = 35
; detect_narrow_internal_solid_infill = 1
; detect_overhang_wall = 1
; detect_thin_wall = 0
; different_settings_to_system = accel_to_decel_enable;bottom_shell_layers;bridge_speed;default_acceleration;default_jerk;enable_arc_fitting;exclude_object;gap_infill_speed;infill_jerk;initial_layer_acceleration;initial_layer_infill_speed;initial_layer_jerk;initial_layer_speed;inner_wall_acceleration;inner_wall_jerk;inner_wall_speed;internal_solid_infill_speed;outer_wall_acceleration;outer_wall_jerk;outer_wall_speed;overhang_2_4_speed;overhang_3_4_speed;overhang_4_4_speed;reduce_crossing_wall;sparse_infill_density;sparse_infill_pattern;sparse_infill_speed;top_surface_acceleration;top_surface_jerk;top_surface_speed;travel_acceleration;travel_speed;wall_loops;close_fan_the_first_x_layers;dont_slow_down_outer_wall;enable_pressure_advance;fan_max_speed;fan_min_speed;filament_flow_ratio;filament_max_volumetric_speed;filament_type;filament_vendor;hot_plate_temp;hot_plate_temp_initial_layer;nozzle_temperature;nozzle_temperature_initial_layer;overhang_fan_speed;
; disable_m73 = 0
; dont_filter_internal_bridges = disabled
; dont_slow_down_outer_wall = 1
; draft_shield = disabled
; during_print_exhaust_fan_speed = 70
; elefant_foot_compensation = 0.15
; elefant_foot_compensation_layers = 1
; emit_machine_limits_to_gcode = 1
; enable_arc_fitting = 0
; enable_filament_ramming = 1
; enable_long_retraction_when_cut = 0
; enable_overhang_bridge_fan = 1
; enable_overhang_speed = 1
; enable_pressure_advance = 1
; enable_prime_tower = 0
; enable_support = 0
; enforce_support_layers = 0
; eng_plate_temp = 0
; eng_plate_temp_initial_layer = 0
; ensure_vertical_shell_thickness = ensure_all
; exclude_object = 1
; extra_loading_move = -2
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height_to_lid = 140
; extruder_clearance_height_to_rod = 36
; extruder_clearance_radius = 65
; extruder_colour = #26A69A
; extruder_offset = 0x0
; fan_cooling_layer_time = 100
; fan_kickstart = 0
; fan_max_speed = 30
; fan_min_speed = 15
; fan_speedup_overhangs = 1
; fan_speedup_time = 0
; filament_colour = #26A69A
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 20
; filament_density = 1.24
; filament_diameter = 1.75
; filament_end_gcode = "; filament end gcode \nM106 P3 S0\n"
; filament_flow_ratio = 0.926
; filament_ids = P510eff9
; filament_is_support = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 30
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Likesilk PLA-F"
; filament_shrink = 100%
; filament_shrinkage_compensation_z = 100%
; filament_soluble = 0
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 0
; filament_start_gcode = "; filament start gcode\n{if  (bed_temperature[current_extruder] >45)||(bed_temperature_initial_layer[current_extruder] >45)}M106 P3 S255\n{elsif(bed_temperature[current_extruder] >35)||(bed_temperature_initial_layer[current_extruder] >35)}M106 P3 S180\n{endif}\n\n{if activate_air_filtration[current_extruder] && support_air_filtration}\nM106 P3 S{during_print_exhaust_fan_speed_num[current_extruder]} \n{endif}"
; filament_toolchange_delay = 0
; filament_type = PLA-F
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Likesilk
; filename_format = {input_filename_base}_{filament_type[0]}_{print_time}.gcode
; filter_out_gap_fill = 0
; first_layer_print_sequence = 0
; flush_into_infill = 0
; flush_into_objects = 0
; flush_into_support = 1
; flush_multiplier = 0.3
; flush_volumes_matrix = 0
; flush_volumes_vector = 140,140
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_first_layer = 0
; fuzzy_skin_point_distance = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_target = nowhere
; gap_infill_speed = 600
; gcode_add_line_number = 0
; gcode_comments = 0
; gcode_flavor = klipper
; gcode_label_objects = 1
; has_scarf_joint_seam = 0
; head_wrap_detect_zone = 
; high_current_on_filament_swap = 0
; hole_to_polyhole = 0
; hole_to_polyhole_threshold = 0.01
; hole_to_polyhole_twisted = 1
; host_type = octoprint
; hot_plate_temp = 65
; hot_plate_temp_initial_layer = 65
; idle_temperature = 0
; independent_support_layer_height = 1
; infill_anchor = 400%
; infill_anchor_max = 20
; infill_combination = 0
; infill_combination_max_layer_height = 100%
; infill_direction = 45
; infill_jerk = 12
; infill_wall_overlap = 15%
; inherits_group = "process template @Voron Microwave 0.4 nozzle";"Generic PLA template @Voron Microwave 0.4 nozzle";
; initial_layer_acceleration = 5000
; initial_layer_infill_speed = 250
; initial_layer_jerk = 12
; initial_layer_line_width = 0.4
; initial_layer_min_bead_width = 85%
; initial_layer_print_height = 0.2
; initial_layer_speed = 250
; initial_layer_travel_speed = 100%
; inner_wall_acceleration = 20000
; inner_wall_jerk = 12
; inner_wall_line_width = 0.4
; inner_wall_speed = 400
; interface_shells = 0
; interlocking_beam = 0
; interlocking_beam_layer_count = 2
; interlocking_beam_width = 0.8
; interlocking_boundary_avoidance = 2
; interlocking_depth = 2
; interlocking_orientation = 22.5
; internal_bridge_flow = 1
; internal_bridge_speed = 150%
; internal_solid_infill_acceleration = 100%
; internal_solid_infill_line_width = 0.4
; internal_solid_infill_pattern = monotonic
; internal_solid_infill_speed = 600
; ironing_angle = -1
; ironing_flow = 10%
; ironing_pattern = zig-zag
; ironing_spacing = 0.15
; ironing_speed = 30
; ironing_type = no ironing
; is_infill_first = 0
; layer_change_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.2
; line_width = 0.4
; long_retractions_when_cut = 0
; machine_end_gcode = PRINT_END
; machine_load_filament_time = 0
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 15000,20000
; machine_max_acceleration_retracting = 5000,5000
; machine_max_acceleration_travel = 20000,20000
; machine_max_acceleration_x = 15000,20000
; machine_max_acceleration_y = 15000,20000
; machine_max_acceleration_z = 500,200
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 15,12
; machine_max_jerk_y = 15,12
; machine_max_jerk_z = 0.2,0.4
; machine_max_speed_e = 25,25
; machine_max_speed_x = 500,200
; machine_max_speed_y = 500,200
; machine_max_speed_z = 12,12
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; machine_pause_gcode = PAUSE
; machine_start_gcode = PRINT_START EXTRUDER_TEMP=[nozzle_temperature_initial_layer] BED_TEMP=[bed_temperature_initial_layer_single]
; machine_tool_change_time = 0
; machine_unload_filament_time = 0
; make_overhang_printable = 0
; make_overhang_printable_angle = 55
; make_overhang_printable_hole_size = 0
; manual_filament_change = 0
; max_bridge_length = 10
; max_layer_height = 0.32
; max_travel_detour_distance = 0
; max_volumetric_extrusion_rate_slope = 0
; max_volumetric_extrusion_rate_slope_segment_length = 3
; min_bead_width = 85%
; min_feature_size = 25%
; min_layer_height = 0.1
; min_length_factor = 0.5
; min_skirt_length = 0
; min_width_top_surface = 300%
; minimum_sparse_infill_area = 15
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; nozzle_height = 2.5
; nozzle_hrc = 0
; nozzle_temperature = 245
; nozzle_temperature_initial_layer = 245
; nozzle_temperature_range_high = 240
; nozzle_temperature_range_low = 190
; nozzle_type = brass
; nozzle_volume = 0
; only_one_wall_first_layer = 0
; only_one_wall_top = 1
; ooze_prevention = 0
; other_layers_print_sequence = 0
; other_layers_print_sequence_nums = 0
; outer_wall_acceleration = 20000
; outer_wall_jerk = 12
; outer_wall_line_width = 0.4
; outer_wall_speed = 400
; overhang_1_4_speed = 0
; overhang_2_4_speed = 100
; overhang_3_4_speed = 60
; overhang_4_4_speed = 40
; overhang_fan_speed = 30
; overhang_fan_threshold = 50%
; overhang_reverse = 0
; overhang_reverse_internal_only = 0
; overhang_reverse_threshold = 50%
; overhang_speed_classic = 0
; parking_pos_retraction = 92
; pellet_flow_coefficient = 0.4157
; pellet_modded_printer = 0
; post_process = 
; precise_outer_wall = 0
; precise_z_height = 0
; preferred_orientation = 0
; preheat_steps = 1
; preheat_time = 30
; pressure_advance = 0.02
; prime_tower_brim_width = 3
; prime_tower_width = 35
; prime_volume = 45
; print_compatible_printers = "Voron Microwave 0.4 nozzle"
; print_flow_ratio = 1
; print_order = default
; print_sequence = by layer
; print_settings_id = Standard @Voron Microwave 0.4 nozzle
; printable_area = 0x0,250x0,250x245,0x245
; printable_height = 200
; printer_model = Voron Microwave
; printer_notes = 
; printer_settings_id = Voron Microwave 0.4 nozzle
; printer_structure = undefine
; printer_technology = FFF
; printer_variant = 0.4
; printhost_authorization_type = key
; printhost_ssl_ignore_revoke = 0
; printing_by_object_gcode = 
; purge_in_prime_tower = 1
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 2
; raft_layers = 0
; reduce_crossing_wall = 1
; reduce_fan_stop_start_freq = 1
; reduce_infill_retraction = 1
; required_nozzle_HRC = 3
; resolution = 0.012
; retract_before_wipe = 70%
; retract_length_toolchange = 2
; retract_lift_above = 0
; retract_lift_below = 0
; retract_lift_enforce = All Surfaces
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_when_changing_layer = 1
; retraction_distances_when_cut = 18
; retraction_length = 0.5
; retraction_minimum_travel = 0.8
; retraction_speed = 35
; role_based_wipe_speed = 1
; rotate_solid_infill_direction = 1
; scan_first_layer = 0
; scarf_angle_threshold = 155
; scarf_joint_flow_ratio = 1
; scarf_joint_speed = 100%
; scarf_overhang_threshold = 40%
; seam_gap = 10%
; seam_position = aligned
; seam_slope_conditional = 0
; seam_slope_entire_loop = 0
; seam_slope_inner_walls = 0
; seam_slope_min_length = 20
; seam_slope_start_height = 0
; seam_slope_steps = 10
; seam_slope_type = none
; silent_mode = 0
; single_extruder_multi_material = 1
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 1
; skirt_loops = 0
; skirt_speed = 50
; skirt_start_angle = -135
; skirt_type = combined
; slice_closing_radius = 0.049
; slicing_mode = regular
; slow_down_for_layer_cooling = 1
; slow_down_layer_time = 4
; slow_down_layers = 0
; slow_down_min_speed = 20
; slowdown_for_curled_perimeters = 1
; small_area_infill_flow_compensation = 0
; small_area_infill_flow_compensation_model = 0,0;"\n0.2,0.4444";"\n0.4,0.6145";"\n0.6,0.7059";"\n0.8,0.7619";"\n1.5,0.8571";"\n2,0.8889";"\n3,0.9231";"\n5,0.9520";"\n10,1"
; small_perimeter_speed = 50%
; small_perimeter_threshold = 0
; solid_infill_direction = 45
; solid_infill_filament = 1
; sparse_infill_acceleration = 100%
; sparse_infill_density = 40%
; sparse_infill_filament = 1
; sparse_infill_line_width = 0.4
; sparse_infill_pattern = honeycomb
; sparse_infill_speed = 600
; spiral_mode = 0
; spiral_mode_max_xy_smoothing = 200%
; spiral_mode_smooth = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_end_points = 30x-3,54x245
; support_air_filtration = 1
; support_angle = 0
; support_base_pattern = default
; support_base_pattern_spacing = 2.5
; support_bottom_interface_spacing = 0.5
; support_bottom_z_distance = 0.2
; support_chamber_temp_control = 1
; support_critical_regions_only = 0
; support_expansion = 0
; support_filament = 0
; support_interface_bottom_layers = 2
; support_interface_filament = 0
; support_interface_loop_pattern = 0
; support_interface_not_for_body = 1
; support_interface_pattern = auto
; support_interface_spacing = 0.5
; support_interface_speed = 80
; support_interface_top_layers = 2
; support_line_width = 0.4
; support_material_interface_fan_speed = -1
; support_multi_bed_types = 0
; support_object_xy_distance = 0.35
; support_on_build_plate_only = 0
; support_remove_small_overhang = 1
; support_speed = 150
; support_style = default
; support_threshold_angle = 30
; support_top_z_distance = 0.2
; support_type = normal(auto)
; temperature_vitrification = 55
; template_custom_gcode = 
; textured_cool_plate_temp = 40
; textured_cool_plate_temp_initial_layer = 40
; textured_plate_temp = 55
; textured_plate_temp_initial_layer = 55
; thick_bridges = 0
; thick_internal_bridges = 1
; thumbnails = 48x48/PNG, 300x300/PNG
; thumbnails_format = PNG
; time_cost = 0
; time_lapse_gcode = 
; timelapse_type = 0
; top_bottom_infill_wall_overlap = 25%
; top_shell_layers = 5
; top_shell_thickness = 0.6
; top_solid_infill_flow_ratio = 1
; top_surface_acceleration = 20000
; top_surface_jerk = 12
; top_surface_line_width = 0.4
; top_surface_pattern = monotonicline
; top_surface_speed = 400
; travel_acceleration = 30000
; travel_jerk = 12
; travel_slope = 3
; travel_speed = 600
; travel_speed_z = 0
; tree_support_adaptive_layer_height = 1
; tree_support_angle_slow = 25
; tree_support_auto_brim = 1
; tree_support_branch_angle = 45
; tree_support_branch_angle_organic = 40
; tree_support_branch_diameter = 2
; tree_support_branch_diameter_angle = 5
; tree_support_branch_diameter_double_wall = 3
; tree_support_branch_diameter_organic = 2
; tree_support_branch_distance = 5
; tree_support_branch_distance_organic = 1
; tree_support_brim_width = 3
; tree_support_tip_diameter = 0.8
; tree_support_top_rate = 30%
; tree_support_wall_count = 0
; upward_compatible_machine = 
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; wall_direction = auto
; wall_distribution_count = 1
; wall_filament = 1
; wall_generator = classic
; wall_loops = 5
; wall_sequence = inner wall/outer wall
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_before_external_loop = 0
; wipe_distance = 1
; wipe_on_loops = 0
; wipe_speed = 80%
; wipe_tower_bridging = 10
; wipe_tower_cone_angle = 0
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_spacing = 100%
; wipe_tower_filament = 0
; wipe_tower_max_purge_speed = 90
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_x = 165.000
; wipe_tower_x = 165,165
; wipe_tower_y = 250.000
; wipe_tower_y = 250,250
; wiping_volumes_extruders = 70,70,70,70,70,70,70,70,70,70
; xy_contour_compensation = 0
; xy_hole_compensation = 0
; z_hop = 0
; z_hop_types = Normal Lift
; z_offset = 0
; first_layer_bed_temperature = 65
; bed_shape = 0x0,250x0,250x245,0x245
; first_layer_temperature = 245
; first_layer_height = 0.200
; CONFIG_BLOCK_END


